### ISSUE TITLE
Build failure when running run-fuzzer.sh

### ISSUE THREAD

**Issue by cardigan1008** [dwrensha/fuzz-rustc#7]
Hi, I'm trying to use this fuzzer but met some problems when running `run-fuzzer.sh`, such as: 

```console
Running `/fuzz-rustc/target/release/build/stacker-af3cf00925ed0b79/build-script-build`
error[E0599]: no method named `sub_ptr` found for raw pointer `*const u8` in the current scope
   --> rust/compiler/rustc_serialize/src/opaque.rs:284:27
    |
284 |         unsafe { self.end.sub_ptr(self.start) }
    |                           ^^^^^^^ method not found in `*const u8`
```
and 

```console
Compiling getrandom v0.2.12                                                                  
     Running `/fuzz-rustc/target/release/build/psm-c12827bb113111b7/build-script-build`         
     Running `/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name g
etrandom...

error[E0599]: no method named `sub_ptr` found for raw pointer `*const u8` in the current scope
   --> rust/compiler/rustc_serialize/src/opaque.rs:290:27
    |
290 |         unsafe { self.end.sub_ptr(self.current) }
    |                           ^^^^^^^ method not found in `*const u8`

error[E0599]: no method named `sub_ptr` found for raw pointer `*const u8` in the current scope
   --> rust/compiler/rustc_serialize/src/opaque.rs:404:31
    |
404 |         unsafe { self.current.sub_ptr(self.start) }
    |                               ^^^^^^^ method not found in `*const u8`
```

The root cause seems to be:

```console
Caused by: process didn't exit successfully: `/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name rustc_serialize --edition=2021 rust/compiler/rustc_serialize/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=96 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=c66972cd94a62a9e -C extra-filename=-2f8bc86cbcf627da --out-dir /fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -C strip=debuginfo -L dependency=/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps -L dependency=/fuzz-rustc/target/release/deps --extern indexmap=/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libindexmap-0a449ed09d7fb651.rmeta --extern smallvec=/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libsmallvec-151647d00871a22a.rmeta --extern thin_vec=/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libthin_vec-a05b346970d7bb5f.rmeta -C passes=sancov-module -C llvm-args=-sanitizer-coverage-level=4 -C llvm-args=-sanitizer-coverage-trace-compares -C llvm-args=-sanitizer-coverage-inline-8bit-counters -C llvm-args=-sanitizer-coverage-pc-table -Z force-unstable-if-unmarked -C debug-assertions=on` (exit status: 1)
```

I tried to specify the nightly version of rustc in the script. However, I didn't know the suitable one so the error still existed. 

Would you have any suggestions on how to resolve this issue? Should I use a specific rustc version or adjust any dependencies? 

Thanks!

**Comment by dwrensha** [comment]
Thanks for the report!

I pushed an update so that the project now runs on the latest rustc: https://github.com/dwrensha/fuzz-rustc/commit/6e873d010c6b6a45f4b86c8c725f6e12d83da9f9

I also updated the [rustc-fork](https://github.com/dwrensha/rust/tree/fuzz) that this project pull from.

**Comment by cicilzx** [comment]
Hi, I'm using the latest version, but it's still not working. This is the error message:

```
error: could not compile `rustc_data_structures` (lib) due to 1 previous error; 1 warning emitted

Caused by:
  process didn't exit successfully: `/home/cici/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name rustc_data_structures --edition=2024 rust/compiler/rustc_data_structures/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=168 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=41e674b21f0817a5 -C extra-filename=-dc494477c39fcb7b --out-dir /home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -C strip=debuginfo -L dependency=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps -L dependency=/home/cici/fuzz-rustc/target/release/deps --extern arrayvec=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libarrayvec-26824f42d460e358.rmeta --extern bitflags=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libbitflags-63f91e1b7eb1ddf5.rmeta --extern either=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libeither-69323fa389e68c58.rmeta --extern elsa=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libelsa-7e811a36ebd9de67.rmeta --extern ena=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libena-0a3b281ff853935a.rmeta --extern hashbrown=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libhashbrown-ba91610c3476ca54.rmeta --extern indexmap=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libindexmap-05cb227f2cbe3ee0.rmeta --extern jobserver_crate=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libjobserver-b956bf5245f52768.rmeta --extern libc=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/liblibc-423173d3e2649e16.rmeta --extern measureme=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libmeasureme-4dff5fc8eae7b471.rmeta --extern memmap2=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libmemmap2-6c26bbee72aeaabb.rmeta --extern parking_lot=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libparking_lot-95cc3b8fff7b71c8.rmeta --extern rustc_hash=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/librustc_hash-3bf45d2c16d957ed.rmeta --extern rayon=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/librayon-42a3018c44e48981.rmeta --extern rustc_stable_hash=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/librustc_stable_hash-c7a8b9b67dc9f276.rmeta --extern rustc_arena=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/librustc_arena-6e6c53a162e29311.rmeta --extern rustc_graphviz=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/librustc_graphviz-fa6393defb4c90fe.rmeta --extern rustc_hashes=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/librustc_hashes-a1cd756f3a357d4e.rmeta --extern rustc_index=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/librustc_index-f7cdae3bdd2534b7.rmeta --extern rustc_macros=/home/cici/fuzz-rustc/target/release/deps/librustc_macros-787d06a7e1fe2227.so --extern rustc_serialize=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/librustc_serialize-a38fc00b4fcae1ab.rmeta --extern smallvec=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libsmallvec-452950cc1cfbb1e0.rmeta --extern stacker=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libstacker-2128f1c44e696179.rmeta --extern tempfile=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libtempfile-4fadc07d52a74e0d.rmeta --extern thin_vec=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libthin_vec-188956324e3a9837.rmeta --extern tracing=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/deps/libtracing-d4f2efe1a248f8aa.rmeta -L /home/cici/.rustup/toolchains/nightly-2024-05-20-x86_64-unknown-linux-gnu/lib -C passes=sancov-module -C llvm-args=-sanitizer-coverage-level=4 -C llvm-args=-sanitizer-coverage-trace-compares -C llvm-args=-sanitizer-coverage-inline-8bit-counters -C llvm-args=-sanitizer-coverage-pc-table -Z force-unstable-if-unmarked -C debug-assertions=on -L native=/home/cici/fuzz-rustc/target/x86_64-unknown-linux-gnu/release/build/psm-cecd4612446941d4/out` (exit status: 1)
warning: build failed, waiting for other jobs to finish...
```

Do I need to switch to a specific version before running `./run-fuzzer.sh`? I tried `rustup override set nightly`, but encounters with this error message:
```
error: cannot find attribute `define_opaque` in this scope
   --> rust/compiler/rustc_data_structures/src/obligation_forest/mod.rs:318:36
    |
318 |         #[cfg_attr(not(bootstrap), define_opaque(ObligationTreeIdGenerator))]
    |                                    ^^^^^^^^^^^^^
```

**Comment by dwrensha** [comment]
> Do I need to switch to a specific version before running `./run-fuzzer.sh`?

Yes, you need to use a recent nightly. I'm using:
```shell
$ rustc --version
rustc 1.87.0-nightly (227690a25 2025-03-16)
```

You may need to run `rustup update` to update your nightly version.
